#!/usr/bin/zsh

# Inspired by:
# https://github.com/jessfraz/dotfiles/blob/master/.dockerfunc
# https://github.com/jessfraz/dockerfiles

export DOCKER_REPO_PREFIX=wardwouts
export DOCKER_COMMAND=podman

# Figure out where the repository lives, to be able to source functions
MYDIR=$(dirname $(realpath $0))
CURDIR=$(pwd)
cd  $MYDIR
export MY_GIT_REPO=$(git rev-parse --show-toplevel)
cd $CURDIR

# Helper functions

del_stopped(){
	local name=$1
	local state
	state=$($DOCKER_COMMAND inspect --format "{{.State.Running}}" "$name" 2>/dev/null)

	if [[ "$state" == "false" ]]; then
		$DOCKER_COMMAND rm "$name"
	fi
}

# /Helper functions

# Source all shell functions from git repository

for funcfile in $(find $MY_GIT_REPO -name func -type f); do
	source $funcfile
done
